a = int(input('Введите первое число '))
b = int(input('Введите второе число '))
print("Сумма чисел", a+b)
print("Разность чисел", a-b)
print("Произведение чисел", a*b)
print("Среднее арифметическое чисел", (a+b)/2 )
max_abs = max(a,b , key=abs)
min_abs = min(a,b , key=abs)
print("Разность максимального и минимального по модулю",abs(max_abs) - abs(min_abs))